### PR TITLE
* introduce new control card VERTEX, and add new code in

### PR DESCRIPTION
**Pull request by rjones30**
GlueXPrimaryGeneratorAction.cc to support it. [rtj]

### CODE REVIEW

**Comment by igjaegle** [comment]
If I understand, the target length has to be specified by the USER? Might it be possible to read it using DGeometry, i.e. be run dependent, so that the USER does not have to take care of that?

**Comment by rjones30** [comment]
Hello igal,

The target length does not have to be specified, but the length of the
"beam spot" does. This is different. The user has control over the
effective size of the interaction zone being requested in the simulation.

-Richard Jones

**Comment by igjaegle** [comment]
Thank you @rjones30. 

@T-Britton , can MCWrapper, find for the (dummy) USER, the target length, and uses it in the new control card?

**Comment by rjones30** [comment]
Igal,

The default value in control.in is the correct value for the liquid
hydrogen target.  I decided not to add the option to look this up in the
geometry (or to add a keyword to use the length of some named volume in the
geometry) because the z-position of the beam spot center is not taken from
the geometry. It is assigned in the "z" column of the "beam_spot" table in
PHOTON_BEAM (see ccdb). Either both the center and the length should come
from the geometry or neither should, and since beam_spot specifies the z
value, I decided that the intent of the beam_spot is to be able to assign
the beam-target fiducial volume independent of the physical limits of the
target volume.

-Richard JOnes

**Comment by igjaegle** [comment]
Then what is happening for measurements that are not using the LH2 target? Do you intend to add an extra column in /PHOTON_BEAM/beam_spot where the target length should be put?

**Comment by rjones30** [comment]
Igal,

That is the beauty of this configuration -- the beam spot specification is
completely user-determined, and not dependent on the geometry. Regardless
of what targets are installed, you can set the beam spot wherever you want
it in your control.in. If you chose to pull this info for the given run
from ccdb, then you will get whatever beam_spot is configured for that run
in ccdb. Obviously if it is a primex run, the beam_spot for that run will
not be the liquid hydrogen target. But regardless of what is in ccdb, you
also have the ability to specify everything directly in the control.in

-Richard Jones

**Comment by aaust** [comment]
Could you add some text output so that the log files show which vertex parameters were used?

**Comment by rjones30** [comment]
Alex, new pull requests have been added for this, both halld_sim and
HDGeant4.
-Richard

**Pull request merged**
