### PR TITLE
Print vertex info if used rtj

### PR DESCRIPTION
**Pull request by rjones30**

### CODE REVIEW

**Comment by aaust** [comment]
Thank you @rjones30 , that is very useful. I get the following output for a simulation of run 30300 with` VERTEX 'beam_spot(ccdb) * 29.5'` in my control.in:

```
G4WT0 > Configured beam vertex parameters: (units of cm)
G4WT0 >    sigma_x=0   sigma_y=0   sigma_xy=0
G4WT0 >    dxdz=0   dydz=0   dz=29.5
```
even though my ccdb tells me this:
```
 ccdb dump PHOTON_BEAM/beam_spot:30300
  0.1296       0.002776     65.          0.04473      0.           0.04261      0.           0.           0.           0.0001720    -0.0001635
```

Where is my mistake?

**Comment by aaust** [comment]
Sorry, the entries for var=mc were actually 0,0,65,...

**Comment by rjones30** [comment]
Alex, let me add the beam spot centroid values as well as the widths, new
update to this PR is coming.
-Richard

**Comment by rjones30** [comment]
PS. If you want var=mc to fall over to default for this table, just delete
the mc variation entries from ccdb and it will automatically grab the
default ones when you ask for mc.
-Richard

**Comment by markito3** [comment]
In principle, we should never delete anything from the CCDB. That defeats the history mechanism. But here such a deletion sounds like it would give us the behavior we want. I think the question is whether or not any past analyses depended on these values from the CCDB for variation=mc. If such dependence is a new feature, introduced by this pull request, then deletion of the obstructing entries would not be a problem.

I don't know the answer to that one.

**Comment by sdobbs** [comment]
I wouldn't delete the entries from the CCDB for the reasons that you give.
We should just enter new data for the mc variation.

I'm waiting to make any changes to the master until we understand the
results of Alex A.'s tests.

**Pull request merged**
