### PR TITLE
Fdc tracking bug fixes rtj

### PR DESCRIPTION
**Pull request by rjones30**

### CODE REVIEW

**Comment by sdobbs** [comment]
We never set up the build test system for this repository, but we could...

**Comment by jrstevenjlab** [comment]
Right, halld_recon and halld_sim are more important, but it wouldn’t hurt to have this built automatically as well.

**Comment by sdobbs** [comment]
I don't mind setting that up (pretty easy under the new scheme), but I'd like to have Richard's approval before I do so

**Comment by jrstevenjlab** [comment]
Of course, no rush.

**Pull request merged**
