### PR TITLE
 make FMWPC wire locations compatible with using cm as units

### PR DESCRIPTION
**Pull request by zihlmann**
for their location. Note these are still hard coded and will need
 a proper treatement using ccdb in the near future.
This also expects to use 6 chambers. and the last one having vertical wires.
Use this in combination with the latest geometry for the chamber which is 
currently only in hddm not in ccdb. This will be updated soon

### CODE REVIEW

**Comment by rjones30** [comment]
Beni,

I took the additional step of making these constants symbolic. They are
still hard-wired but now they have names and an explanation of their
meaning, in anticipation that they might someday be updated from ccdb. Have
a look.

-Richard J.

**Comment by zihlmann** [comment]
the code "/cm" got dropped which will result in comparing mm to cm since the x[i] values are in mm not cm.

**Comment by rjones30** [comment]
Beni, can you look again?
-Richard

**Comment by zihlmann** [comment]
// Vertical wires
         wire = floor(x[0]/cm + 73.0);
         wire = floor(x[0] - WIRE_OFFSET)/WIRE_PITCH;

the difference between these two lines of codes is that in the first we have x[0]/cm to make it to units of "cm" 
while in the second line we only have x[0] which is in unites of "mm" while the value WIRE_OFFSET is in unites of "cm" 

or am I missing something?

**Comment by eltonssmith** [comment]
Is there a reason that we do not simply do everything in mm? That would make it consistent with the GEANT units. Notes in the code can emphasize that values are in mm.

**Comment by zihlmann** [comment]
remember many many years ago (when we also still used geant3) we decided to use the units
cm, ns, GeV, GeV/c ......
as a result hopefully all values in ccdb are in those units where needed.

**Comment by rjones30** [comment]
Beni,

You are missing something here. The definition of WIRE_OFFSET and
WIRE_PITCH are

double GlueXSensitiveDetectorFMWPC::WIRE_OFFSET = -73.0*cm;
double GlueXSensitiveDetectorFMWPC::WIRE_PITCH = 1.0*cm;

The "*cm" factor has a numerical value of 10. This notation "73*cm" means
assign this variable a length of 73 cm in whatever length units are in use
in this context".

-Richard

**Comment by rjones30** [comment]
The principle in G4 is to be units-agnostic. If you have a constant with
units you always write it as value*unit which makes the code much more
readable. This does not need to be over-thought -- just follow the G4
convention, it is better than G3 in this regard.
-Richard Jones

**Comment by rjones30** [comment]
PS. That is, in the G4 code itself.
In ccdb, the quantities all need to carry only their units. I suggest a
notation like wire_offset_cm or signal_thresh_keV for constants in the ccdb
that need to carry units.
-Richard

**Comment by zihlmann** [comment]
thank you!
yes I missed the cm in the definition of the variable.

**Pull request merged**
