### PR TITLE
fix bug in loop to add hits to wires list put the } at the right place.

### PR DESCRIPTION
**Pull request by zihlmann**
second attempt to get this into the JeffersonLab GEANT4 repo master

### CODE REVIEW

**Comment by rjones30** [comment]
I already merged these changes in, so the master branch contains this fix. Thank you for finding and fixing it!

**Comment by markito3** [comment]
@rjones30 , Beni mistakenly submitted this pull request to the rjones30/HDGeant4 repository. You merged it in there. This is indeed the same pull request, a duplicate, but aimed at the JeffersonLab/HDGeant4 repository, which does not have the fix yet. I am re-opening it...

**Comment by markito3** [comment]
but now there is a conflict, so I am confused...closing...

**Comment by rjones30** [comment]
Mark, it is already done. The fix is in the master.
-Richard

**Pull request closed without merging**
