### PR TITLE
New bethe heitler internal generator rtj

### PR DESCRIPTION
**Pull request by rjones30**

### CODE REVIEW

**Comment by aaust** [comment]
I am having trouble building hdgeant4 since this pull request went in. Anybody observe the same?

Am I missing a package? Here is the compiler error:
```
src/GlueXBeamConversionProcess.cc: In destructor ‘virtual GlueXBeamConversionProcess::~GlueXBeamConversionProcess()’:
src/GlueXBeamConversionProcess.cc:146:8: error: ‘sampler_initialized’ was not declared in this scope
    if (sampler_initialized)
        ^
src/GlueXBeamConversionProcess.cc:147:7: error: ‘sampler’ was not declared in this scope
       sampler.saveState("BHgen_stats.astate");

make: *** [/w/halld-scifs17exp/halld2/home/aaustreg/Analysis/sw/hdpm/hdgeant4/master/tmp/Linux-g++/hdgeant4/GlueXBeamConversionProcess.o] Error 1
make: *** Waiting for unfinished jobs....
2020/06/04 17:40:26 exit status 2
```

**Comment by rjones30** [comment]
Looking at it now,
-Richard

**Comment by rjones30** [comment]
Alex,

Can you make sure that the symbol DIRACXX_HOME is being properly defined in
your environment setup?

-Richard Jones

**Comment by rjones30** [comment]
Alex, I added protection against environments where DIRACXX_HOME is not
properly defined. Please try again now.
-Richard

**Comment by aaust** [comment]
It works, thank you. Where does the DIRACXX come from? I am keeping my build as light as possible.

**Comment by rjones30** [comment]
DIRACXX is general library for calculating QED processes with full
polarization dependence by summing all diagrams up through tree level. It
is needed for TPOL simulations, and the new Bethe Heitler process, and for
an exact calculation of the beam polarization structure beyond the simple
model implemented in hdgeant. That simple model has been ported to hdgeant4
for use by people who don't want to build the full DIRACXX package and link
against it. I am supporting this minimal mode and I know you are not alone
in wanting to work this way. Sorry for the snafu with the build earlier
today.

-Richard Jones

**Pull request merged**
